### ISSUE TITLE
How to remote from Windows 10 using remote desktop

### ISSUE THREAD

**Issue by vedranmarkulj** [RattyDAVE/docker-ubuntu-xrdp-mate-custom#3]
Hi, I have followed your instructions from ubuntu 19.04. I have build the image and running the container. However, I am not able to connect to the container using remote desktop. I am using the adress 0.0.0.0 to connect but the server cannot be found. Do I have to use a different ip adress, and how to find that adress?

### The run command I used:
```
docker run -it --name xrdp-ubuntu-1904 --privileged=true -p 3389:3389 -v /createusers.txt:/root/createusers.txt -v /home:/home -dit --restart unless-stopped xrdp-ubuntu-1904:19.04
```

### Docker ps
```
CONTAINER ID        IMAGE                    COMMAND             CREATED             STATUS              PORTS                    NAMES
05ed3697d89e        xrdp-ubuntu-1904:19.04   "/bin/bash"         23 minutes ago      Up 23 minutes       0.0.0.0:3389->3389/tcp   xrdp-ubuntu-1904
```

**Comment by RattyDAVE** [comment]
It is the IP address of the docker host machine. So where you did your ```docker ps```

What 0.0.0.0 means is ALL IP interfaces. It is not a usable IP address.

Do you have a docker server and a clicnet machine you are using to access? Or is it all on the same machine? 

If on the same machine you can use 127.0.0.1

DAVE

**Comment by vedranmarkulj** [comment]
Thanks Dave,

Your solution resolved my issue.

I run everything on the same machine, therefore 127.0.0.1 works.
I had to map the port to a different port e.g. 33891:3389 because if I mapped 3389:3389 I kept getting a message "Your computer could not connect to another console session on the remote computer because you already have a console session in progress" when trying to remote connect.

However, everything works now, thanks again for the help, and very quick reply.

**Comment by RattyDAVE** [comment]
That's ok... seems you did this the hard way... and not use the pre built docker hub one..On 28 Jul 2019 13:11, vedranmarkulj <notifications@github.com> wrote:Thanks Dave,
Your solution resolved my issue.
I run everything on the same machine, therefore 127.0.0.1 works.
I had to map the port to a different port e.g. 33891:3389 because if I mapped 3389:3389 I kept getting a message "Your computer could not connect to another console session on the remote computer because you already have a console session in progress" when trying to remote connect.
However, everything works now, thanks again for the help, and very quick reply.
