### ISSUE TITLE
A version that works.... Pre alpha alpha alpha alpha alpha alpha alpha alpha alpha alpha 

### ISSUE THREAD

**Issue by RattyDAVE** [RattyDAVE/docker-ubuntu-xrdp-mate-custom#8]
New Tag for testing. This WILL cause issues. This WILL break. And it WILL drink all your beer!

So with that in mind.....

**Comment by alturismo** [comment]
1st try ;)

`'Supervisord is running as root and it is searching '
2019-10-08 21:39:47,234 CRIT Supervisor is running as root. Privileges were not dropped because no user is specified in the config file. If you intend to run as root, you can set user=root in the config file to avoid this message.
2019-10-08 21:39:47,234 INFO Included extra file "/etc/supervisor/conf.d/xrdp.conf" during parsing
2019-10-08 21:39:47,239 INFO RPC interface 'supervisor' initialized
2019-10-08 21:39:47,239 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2019-10-08 21:39:47,239 INFO supervisord started with pid 1170
2019-10-08 21:39:48,239 INFO spawnerr: can't find command '/usr/local/sbin/xrdp-sesman'
2019-10-08 21:39:48,240 INFO spawnerr: can't find command '/usr/local/sbin/xrdp'
2019-10-08 21:39:49,240 INFO spawnerr: can't find command '/usr/local/sbin/xrdp-sesman'
2019-10-08 21:39:49,241 INFO spawnerr: can't find command '/usr/local/sbin/xrdp'
2019-10-08 21:39:51,242 INFO spawnerr: can't find command '/usr/local/sbin/xrdp-sesman'
2019-10-08 21:39:51,243 INFO spawnerr: can't find command '/usr/local/sbin/xrdp'
2019-10-08 21:39:54,245 INFO spawnerr: can't find command '/usr/local/sbin/xrdp-sesman'
2019-10-08 21:39:54,246 INFO gave up: xrdp-sesman entered FATAL state, too many start retries too quickly
2019-10-08 21:39:54,246 INFO spawnerr: can't find command '/usr/local/sbin/xrdp'
2019-10-08 21:39:54,246 INFO gave up: xrdp entered FATAL state, too many start retries too quickly`

**Comment by RattyDAVE** [comment]
Oh great you got another old version.The new one should be there shortly..If you don't want to pull... edit the /etc/supervisor/xrdp file and remove local out of the directorys... then restart..On 8 Oct 2019 20:42, alturismo <notifications@github.com> wrote:1st try ;)
'Supervisord is running as root and it is searching ' 2019-10-08 21:39:47,234 CRIT Supervisor is running as root. Privileges were not dropped because no user is specified in the config file. If you intend to run as root, you can set user=root in the config file to avoid this message. 2019-10-08 21:39:47,234 INFO Included extra file "/etc/supervisor/conf.d/xrdp.conf" during parsing 2019-10-08 21:39:47,239 INFO RPC interface 'supervisor' initialized 2019-10-08 21:39:47,239 CRIT Server 'unix_http_server' running without any HTTP authentication checking 2019-10-08 21:39:47,239 INFO supervisord started with pid 1170 2019-10-08 21:39:48,239 INFO spawnerr: can't find command '/usr/local/sbin/xrdp-sesman' 2019-10-08 21:39:48,240 INFO spawnerr: can't find command '/usr/local/sbin/xrdp' 2019-10-08 21:39:49,240 INFO spawnerr: can't find command '/usr/local/sbin/xrdp-sesman' 2019-10-08 21:39:49,241 INFO spawnerr: can't find command '/usr/local/sbin/xrdp' 2019-10-08 21:39:51,242 INFO spawnerr: can't find command '/usr/local/sbin/xrdp-sesman' 2019-10-08 21:39:51,243 INFO spawnerr: can't find command '/usr/local/sbin/xrdp' 2019-10-08 21:39:54,245 INFO spawnerr: can't find command '/usr/local/sbin/xrdp-sesman' 2019-10-08 21:39:54,246 INFO gave up: xrdp-sesman entered FATAL state, too many start retries too quickly 2019-10-08 21:39:54,246 INFO spawnerr: can't find command '/usr/local/sbin/xrdp' 2019-10-08 21:39:54,246 INFO gave up: xrdp entered FATAL state, too many start retries too quickly

**Comment by RattyDAVE** [comment]
Just checked it is still uploading. 

Quick fix is to edit ```/etc/supervisor/conf.d/xrdp.conf```

So that this line ```/usr/local/sbin/xrdp``` is now ```/usr/sbin/xrdp```
and the same for
```/usr/local/sbin/xrdp-sesman``` to ```/usr/sbin/xrdp-sesman```

So once in type mate-session to get to what you know.

So what this has, that is diffent is the xrdp, xrdp-sessman, xorg, pulseaudio are compiled. Then prepackaged and then installed. In a very diffent way to the other builds.

I think I am 99% there but still not quite got got it.. I think dbus may be key. Still looking.

**Comment by alturismo** [comment]
its starting, but no desktop coming up, only console

![screenshot](https://user-images.githubusercontent.com/8406490/66432939-805d6180-ea1f-11e9-8127-2c3669ea77b7.png)

**Comment by RattyDAVE** [comment]
So once in type mate-session to get to what you know

**Comment by RattyDAVE** [comment]
So once in type mate-session to get to what you know.

I am our all day today so there will be no changes today.

**Comment by alturismo** [comment]
tried it, here a screen from session start with some error messages.
![1910test1](https://user-images.githubusercontent.com/8406490/66539534-930f8d80-eb28-11e9-8e5f-8c77dd84e6e0.PNG)

**Comment by RattyDAVE** [comment]
its a mess with the dbus

I would not bother reporting errors...

**Comment by RattyDAVE** [comment]
Spent alot of time on this yesterday... seems 19.10 is not the best to do this on....

**Comment by alturismo** [comment]
ok, very nice you tried it ;)

**Comment by RattyDAVE** [comment]
New version ready soon... its proof of concept... and way too complicated .... sound works ... just.... video acceleration too...

I am not at all happy with it.. but it can be done.... oh and it is based on 18.04

**Comment by RattyDAVE** [comment]
docker run -dit --restart unless-stopped --name RattyDAVE19.10test \
           --privileged=true \
           -p 3390:3389 \
           --shm-size 1g \
           -e TZ="Europe/London" \
           -e DISABLE_GPU="False" \
           -v createusers.txt:/root/createusers.txt \
           -v startup.sh:/root/startup.sh \
           -v home:/home \
           rattydave/docker-ubuntu-xrdp-mate-custom:test

**Comment by RattyDAVE** [comment]
No more changes for today...

**Comment by RattyDAVE** [comment]
Have you tried this version yet?

**Comment by alturismo** [comment]
fast test, but with /_root/.... not /root/

from the log if that helps

Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
The following NEW packages will be installed:
ssl-cert
The following packages have been kept back:
xorgxrdp
The following packages will be upgraded:
base-files dpkg e2fsprogs grep libext2fs2 libss2 xrdp
7 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 2,350 kB of archives.
After this operation, 2,150 kB disk space will be freed.
Get:1 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 base-files amd64 10.1ubuntu2.7 [60.3 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 dpkg amd64 1.19.0.5ubuntu2.3 [1,136 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libext2fs2 amd64 1.44.1-1ubuntu1.2 [157 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 e2fsprogs amd64 1.44.1-1ubuntu1.2 [390 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 grep amd64 3.1-2build1 [159 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libss2 amd64 1.44.1-1ubuntu1.2 [11.1 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic/main amd64 ssl-cert all 1.0.39 [17.0 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic/universe amd64 xrdp amd64 0.9.5-2 [419 kB]
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Fetched 2,350 kB in 7s (315 kB/s)
Preparing to unpack .../base-files_10.1ubuntu2.7_amd64.deb ...
Unpacking base-files (10.1ubuntu2.7) over (10.1ubuntu2.6) ...
Setting up base-files (10.1ubuntu2.7) ...
Installing new version of config file /etc/update-motd.d/50-motd-news ...

Preparing to unpack .../dpkg_1.19.0.5ubuntu2.3_amd64.deb ...
Unpacking dpkg (1.19.0.5ubuntu2.3) over (1.19.0.5ubuntu2.2) ...
Setting up dpkg (1.19.0.5ubuntu2.3) ...
Preparing to unpack .../libext2fs2_1.44.1-1ubuntu1.2_amd64.deb ...
Unpacking libext2fs2:amd64 (1.44.1-1ubuntu1.2) over (1.44.1-1ubuntu1.1) ...
Setting up libext2fs2:amd64 (1.44.1-1ubuntu1.2) ...
Preparing to unpack .../e2fsprogs_1.44.1-1ubuntu1.2_amd64.deb ...
Unpacking e2fsprogs (1.44.1-1ubuntu1.2) over (1.44.1-1ubuntu1.1) ...
Setting up e2fsprogs (1.44.1-1ubuntu1.2) ...
Preparing to unpack .../grep_3.1-2build1_amd64.deb ...
Unpacking grep (3.1-2build1) over (3.1-2) ...
Setting up grep (3.1-2build1) ...
Preparing to unpack .../libss2_1.44.1-1ubuntu1.2_amd64.deb ...
Unpacking libss2:amd64 (1.44.1-1ubuntu1.2) over (1.44.1-1ubuntu1.1) ...
Setting up libss2:amd64 (1.44.1-1ubuntu1.2) ...
Selecting previously unselected package ssl-cert.
Preparing to unpack .../ssl-cert_1.0.39_all.deb ...
Unpacking ssl-cert (1.0.39) ...
Preparing to unpack .../xrdp_0.9.5-2_amd64.deb ...
Unpacking xrdp (0.9.5-2) over (0-0) ...
Setting up ssl-cert (1.0.39) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
Setting up xrdp (0.9.5-2) ...
Installing new version of config file /etc/default/xrdp ...

Installing new version of config file /etc/init.d/xrdp ...

Installing new version of config file /etc/xrdp/pulse/default.pa ...


Configuration file '/etc/xrdp/sesman.ini'
==> Modified (by you or by a script) since installation.
==> Package distributor has shipped an updated version.

What would you like to do about it ? Your options are:
Y or I : install the package maintainer's version

N or O : keep your currently-installed version

D : show the differences between the versions
Z : start a shell to examine the situation
The default action is to keep your current version.

*** sesman.ini (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package xrdp (--configure):

end of file on stdin at conffile prompt
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for plymouth-theme-ubuntu-text (0.9.3-1ubuntu7.18.04.2) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Processing triggers for systemd (237-3ubuntu10.31) ...
Errors were encountered while processing:
xrdp
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by RattyDAVE** [comment]
Very confused on where these messages are comming from....

It looks like you are are doing an update? (should never do on docker containers...)

Just try withe the following options...

```
docker run -dit --restart unless-stopped --name RattyDAVE19.10test
--privileged=true
-p 3390:3389
--shm-size 1g
-v createusers.txt:/root/createusers.txt
-v home:/home
rattydave/docker-ubuntu-xrdp-mate-custom:test
```

make sure the home is blank.... as this will over write and or use existing stuff...

**Comment by alturismo** [comment]
release 18.04, Strike ;) Audio check !!!

**Comment by RattyDAVE** [comment]
So now I am making changes... expect breakages!

**Comment by alturismo** [comment]
insane, thanks alot for your efforts to make this working ;)

**Comment by alturismo** [comment]
some feedback after some testing

sound working nice on all my clients, win rdp, guacamole, remmina ;) TOP

some things compared to 19.10, vaapi gstream is not working, wine has issues with tcp, ip stack it seems

**Comment by RattyDAVE** [comment]
Not worth worring about things at the moment... Things are changing rapidly.....

The current version is back on MATE. No firefox.. I have way too many packages installed and stripping down. 


Also in the version as of time of writing..... has the GPU accelleration disabled. As was causing incompatabilities.... (startup script is in /etc/supervisor/conf.d/xdummy.conf.new)

**Comment by RattyDAVE** [comment]
I have tried 19.10 and that does not work. 

18.04 seems to be the stable version.

**Comment by alturismo** [comment]
too bad ;)

i ll look into my personal issues then with 18 04, so i can decide stay on 19.10 without sound or get 18.04 running with my usecase.

**Comment by RattyDAVE** [comment]
Just a note 19.10 is not official released yet.. also it is not LTS version.... 

20.04 will be the stable version...

**Comment by alturismo** [comment]
i know ;) i stay on 19:10 for now cause the other issues where finally too much now. with the :test branch.

thanks and lets see what time will bring with sound support, at least we figured its possible ;)

**Comment by alturismo** [comment]
and i had a update for 19:10, wich breaked now here rdp

i didnt wanted to add a new issue

from the log

`Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
/usr/lib/python2.7/dist-packages/supervisor/options.py:461: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
'Supervisord is running as root and it is searching '
2019-10-14 18:44:12,312 CRIT Supervisor is running as root. Privileges were not dropped because no user is specified in the config file. If you intend to run as root, you can set user=root in the config file to avoid this message.
2019-10-14 18:44:12,312 INFO Included extra file "/etc/supervisor/conf.d/dbus-daemon.conf" during parsing
2019-10-14 18:44:12,312 INFO Included extra file "/etc/supervisor/conf.d/xrdp.conf" during parsing
Unlinking stale socket /var/run/supervisor.sock
2019-10-14 18:44:12,616 INFO RPC interface 'supervisor' initialized
2019-10-14 18:44:12,616 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2019-10-14 18:44:12,616 INFO supervisord started with pid 1531
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
/usr/lib/python2.7/dist-packages/supervisor/options.py:461: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
'Supervisord is running as root and it is searching '
2019-10-14 18:44:12,312 CRIT Supervisor is running as root. Privileges were not dropped because no user is specified in the config file. If you intend to run as root, you can set user=root in the config file to avoid this message.
2019-10-14 18:44:12,312 INFO Included extra file "/etc/supervisor/conf.d/dbus-daemon.conf" during parsing
2019-10-14 18:44:12,312 INFO Included extra file "/etc/supervisor/conf.d/xrdp.conf" during parsing
Unlinking stale socket /var/run/supervisor.sock
2019-10-14 18:44:12,616 INFO RPC interface 'supervisor' initialized
2019-10-14 18:44:12,616 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2019-10-14 18:44:12,616 INFO supervisord started with pid 1531
2019-10-14 18:44:13,617 INFO spawned: 'xrdp-sesman' with pid 1534
2019-10-14 18:44:13,618 INFO spawned: 'xrdp' with pid 1535
2019-10-14 18:44:13,618 INFO spawnerr: can't find command '/usr/bin/chpst'
2019-10-14 18:44:14,619 INFO success: xrdp-sesman entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-10-14 18:44:14,619 INFO success: xrdp entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-10-14 18:44:14,619 INFO spawnerr: can't find command '/usr/bin/chpst'
2019-10-14 18:44:16,621 INFO spawnerr: can't find command '/usr/bin/chpst'
2019-10-14 18:44:19,624 INFO spawnerr: can't find command '/usr/bin/chpst'
2019-10-14 18:44:19,624 INFO gave up: dbus-daemon entered FATAL state, too many start retries too quickly
2019-10-14 18:44:19,624 INFO spawnerr: can't find command '/usr/bin/chpst'
2019-10-14 18:44:19,624 INFO gave up: dbus-daemon entered FATAL state, too many start retries too quickly`

**Comment by RattyDAVE** [comment]
When you get that? That SHOULD of been fixed quickly.... There was another one that was uploaded 1 hour ago.... that fixed that.....

**Comment by RattyDAVE** [comment]
I made the 19.10 a more cleaner install... (once I am happy with it ill drop the latest tag on it... )

**Comment by alturismo** [comment]
;) then i ve been too fast ;)

**Comment by alturismo** [comment]
just as note in case i missunderstood, 19 10, just reinstalled plain, same error as note, forget this message in case u still updating ;)

docker start log
---
Current default time zone: 'Europe/Berlin'
Local time is now: Tue Oct 15 08:59:52 CEST 2019.
Universal Time is now: Tue Oct 15 06:59:52 UTC 2019.

Username: alturismo, Password: pass , Sudo: Y
Username: user2, Password: pass , Sudo: Y
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package htop
/usr/lib/python2.7/dist-packages/supervisor/options.py:461: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
'Supervisord is running as root and it is searching '
2019-10-15 08:59:53,400 CRIT Supervisor is running as root. Privileges were not dropped because no user is specified in the config file. If you intend to run as root, you can set user=root in the config file to avoid this message.
2019-10-15 08:59:53,400 INFO Included extra file "/etc/supervisor/conf.d/dbus-daemon.conf" during parsing
2019-10-15 08:59:53,401 INFO Included extra file "/etc/supervisor/conf.d/xrdp.conf" during parsing
2019-10-15 08:59:53,405 INFO RPC interface 'supervisor' initialized
2019-10-15 08:59:53,405 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2019-10-15 08:59:53,405 INFO supervisord started with pid 109
2019-10-15 08:59:54,406 INFO spawned: 'xrdp-sesman' with pid 112
2019-10-15 08:59:54,407 INFO spawned: 'xrdp' with pid 113
2019-10-15 08:59:54,407 INFO spawnerr: can't find command '/usr/bin/chpst'
2019-10-15 08:59:55,408 INFO success: xrdp-sesman entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-10-15 08:59:55,408 INFO success: xrdp entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-10-15 08:59:55,408 INFO spawnerr: can't find command '/usr/bin/chpst'
2019-10-15 08:59:57,410 INFO spawnerr: can't find command '/usr/bin/chpst'
2019-10-15 09:00:00,413 INFO spawnerr: can't find command '/usr/bin/chpst'
2019-10-15 09:00:00,413 INFO gave up: dbus-daemon entered FATAL state, too many start retries too quickly
---
attached from rdp screen

have a good day
![screenshot](https://user-images.githubusercontent.com/8406490/66808100-d56f0b00-ef2a-11e9-8501-299e4abe0563.png)

**Comment by RattyDAVE** [comment]
This is odd.

hub.docker says it has the right version. And looking at the build it says it has the right version. 

can you double check and do a 

`
docker pull rattydave/docker-ubuntu-xrdp-mate-custom:19.10
`

While you are doing that I will do a rebuild anyway. (its just one button press)

**Comment by RattyDAVE** [comment]
Ill update when the rebuild finishes.. (normally about 45 mins)

**Comment by alturismo** [comment]
i did use the tag 19.10, never used :latest, just as note

**Comment by RattyDAVE** [comment]
Found the problem.

Seems Ubuntu made a few changes to 19.10 before release.  (was expected)

Bit longer to fix....

**Comment by alturismo** [comment]
good (or may not so good) news, so i didnt messed it up here at least ;)

**Comment by alturismo** [comment]
and maybe the reason why your sound addition didnt work out ?

**Comment by RattyDAVE** [comment]
So 19.10 is not offically released yet.. so still changes and breakages are expected... 

The change between 18.04 and 19.10 is huge. 

And the sound.. well I think that is do do with Wayland support.

https://wiki.ubuntu.com/EoanErmine/ReleaseNotes

**Comment by RattyDAVE** [comment]
New version uploaded...

**Comment by RattyDAVE** [comment]
Another version uploaded...Functional the same... but with less layers and smaller footprint.

The joy of working with ever changed code...

**Comment by alturismo** [comment]
basically the same error as before, in the end

19.10 tagged, tried also clean start (no user dirs ... no startup entries)
->
2019-10-15 13:44:09,131 INFO exited: dbus-daemon (exit status 1; not expected)
2019-10-15 13:44:10,132 INFO success: xrdp-sesman entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-10-15 13:44:10,132 INFO success: xrdp entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-10-15 13:44:10,132 INFO spawned: 'dbus-daemon' with pid 34
2019-10-15 13:44:10,137 INFO exited: dbus-daemon (exit status 1; not expected)
2019-10-15 13:44:12,139 INFO spawned: 'dbus-daemon' with pid 35
2019-10-15 13:44:12,144 INFO exited: dbus-daemon (exit status 1; not expected)
2019-10-15 13:44:12,139 INFO spawned: 'dbus-daemon' with pid 35
2019-10-15 13:44:12,144 INFO exited: dbus-daemon (exit status 1; not expected)
2019-10-15 13:44:15,148 INFO spawned: 'dbus-daemon' with pid 36
2019-10-15 13:44:15,154 INFO exited: dbus-daemon (exit status 1; not expected)
2019-10-15 13:44:16,155 INFO gave up: dbus-daemon entered FATAL state, too many start retries too quickly
2019-10-15 13:44:16,155 INFO gave up: dbus-daemon entered FATAL state, too many start retries too quickly
<-

**Comment by RattyDAVE** [comment]
You should sill be able to connect...

**Comment by RattyDAVE** [comment]
19.10 is playing with the DBUS stuff...

**Comment by alturismo** [comment]
so, i finally found a way to use them again, now both are working ...

tags 19.10 and test

i always have to chmod -R 777 /home/username .... the i can login
the test (18.04) mate version is also working with sound like this, just as note, just a little slower ...

**Comment by alturismo** [comment]
and final note after some tests now here again, both versions not as fluid as before, xrandr seems broken, rdp screen takes a while until it even comes up, ... may revert some changes ?

**Comment by RattyDAVE** [comment]
I think you have an issue with your home drive.

I would remove and let the container recreate with the correct permissions. (also the hidden dirs and files)

Sharing like that will have unpridictable results as the UID will be different on each container. Also the xwindows config files will be different between versions.

**Comment by RattyDAVE** [comment]
The only versions that have been touched is the 19.10 (and that is not released yet) and the TEST and that was just a test. 

I think Ubuntu 19.10 will be released on the 17th Oct so should be better after then. 

If you want stability then the 18.04 is the one you want..

**Comment by alturismo** [comment]
hi, dont bother, just wanted to let you know out of the testings the last week i made that meanwhile the test and the 19.10 has these issues which where not there before, thats all ;)
.ICEauthority .... and yes, when i pass this error (takes some time) its all good and smooth, but this lasts only until a restart, then its the same procedure again.

as note, same on the 19.04, i didnt looked for the normal 18.04 yet, will give that a try then too.

and of course tested with empty and clear setup (fresh docker and fresh mounts), thats why i apprechiate the setup script procedure.

**Comment by alturismo** [comment]
small feedback after running the test branch for the last 2 weeks, all stable, all good

one thing (no idea if known) is the Desktop is not working as dashboard, no files, no right click menu, ...

rest is rock solid, sound is fine, all good ;)

**Comment by RattyDAVE** [comment]
On ```test``` no desktop? Thats strange as fine on mine. Anyway I am not too bothered. As I am going to move ```19.10``` over to ```latest``` and remove the old versions.

And create a new tag of ```stable``` that will point to ```18.04```

**Comment by alturismo** [comment]
yes, on test there is no desktop here (blank), no shortcuts, no right click possible, ... nvm ;)
will 19.10 also get sound support or you gonna keep this on 18.04 only for now ?
i wait for the update ;)

**Comment by RattyDAVE** [comment]
All the 19.xx versions are not worth the time to change. (It all works fine on mine)
the 20.04 is where it is at now.

Thats going up now!

**Comment by RattyDAVE** [comment]
Use https://github.com/RattyDAVE/docker-ubuntu-xrdp-mate-custom/issues/10 for 20.04 talk

**Comment by alturismo** [comment]
ready for 20 ;)

last question here, stable 18.04 is included sound suport ?

**Comment by RattyDAVE** [comment]
No its not.
